name = "cloudflare-docker-proxy3"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "lng-ai.com"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "lng-ai.com"

[env.production]
name = "cloudflare-docker-proxy3"
# routes = [
#   { pattern = "docker.lng-ai.com", custom_domain = true },
#   { pattern = "quay.lng-ai.com", custom_domain = true },
#   { pattern = "gcr.lng-ai.com", custom_domain = true },
#   { pattern = "k8s-gcr.lng-ai.com", custom_domain = true },
#   { pattern = "k8s.lng-ai.com", custom_domain = true },
#   { pattern = "ghcr.lng-ai.com", custom_domain = true },
#   { pattern = "cloudsmith.lng-ai.com", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy3-staging"
# route = { pattern = "docker-staging.lng-ai.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
